// src/components/layout/Footer.tsx
import Link from "next/link";
import {
  FaInstagram,
  FaXTwitter,
  FaYoutube,
  FaBookOpen,
  FaHeart,
} from "react-icons/fa6";
import { FaGoodreadsG } from "react-icons/fa";
import styles from "./Footer.module.css";

const SECTIONS = [
  { href: "/", label: "Inicio" },
  { href: "/book-review", label: "Reseñas" },
  { href: "/blog", label: "Blog" },
  { href: "/tbr", label: "TBR" },
  { href: "/authors", label: "Autores" },
  { href: "/about-me", label: "Sobre mí" },
];

const CATEGORIES = [
  { href: "/blog?categoria=arc-review", label: "ARC Reviews" },
  { href: "/blog?categoria=monthly-wrap-up", label: "Monthly Wrap-Up" },
  { href: "/blog?categoria=www-wednesday", label: "WWW Wednesday" },
  { href: "/blog?categoria=top-10-tuesday", label: "Top 10 Tuesday" },
];

const SOCIAL = [
  { href: "#", icon: <FaInstagram />, label: "Instagram" },
  { href: "#", icon: <FaXTwitter />, label: "Twitter / X" },
  { href: "#", icon: <FaGoodreadsG />, label: "Goodreads" },
  { href: "#", icon: <FaYoutube />, label: "YouTube" },
  { href: "#", icon: <FaBookOpen />, label: "NetGalley" },
];

export default function Footer() {
  return (
    <footer className={styles.footer}>
      <div className="container">
        <div className={styles.footerContent}>
          <div className={styles.footerBrand}>
            <h3>Yolit&apos;s Bookish</h3>
            <p>
              Compulsive Reader, Book Blogger &amp; Reviewer. Tu guía literaria
              bilingüe.
            </p>
            <div className={styles.socialLinks}>
              {SOCIAL.map(({ href, icon, label }) => (
                <a
                  key={label}
                  href={href}
                  aria-label={label}
                  className={styles.socialLink}
                >
                  {icon}
                </a>
              ))}
            </div>
          </div>

          <div className={styles.footerLinks}>
            <h4>Secciones</h4>
            <ul>
              {SECTIONS.map(({ href, label }) => (
                <li key={href}>
                  <Link href={href}>{label}</Link>
                </li>
              ))}
            </ul>
          </div>

          <div className={styles.footerLinks}>
            <h4>Categorías</h4>
            <ul>
              {CATEGORIES.map(({ href, label }) => (
                <li key={label}>
                  <Link href={href}>{label}</Link>
                </li>
              ))}
            </ul>
          </div>

          <div className={styles.footerLinks}>
            <h4>Contacto</h4>
            <ul>
              <li>
                <a href="mailto:hola@yolitsbookish.com">
                  hola@yolitsbookish.com
                </a>
              </li>
              <li>
                <Link href="/review-policy">Política de Reseñas</Link>
              </li>
            </ul>
          </div>
        </div>

        <div className={styles.copyright}>
          <span>
            &copy; {new Date().getFullYear()} Yolit&apos;s Bookish. Todos los
            derechos reservados. | Diseñado con
          </span>
          <FaHeart className={styles.heart} />
          <span>y muchas páginas leídas.</span>
        </div>
      </div>
    </footer>
  );
}

// app/components/UI/Footer.vue
<script setup>
const titleFooter = "Yolit's Bookish";
const subTitleFooter = 'Compulsive Reader, Book Blogger and Reviewer';
</script>
<template>
	<footer id="footer" class="bg-purple-800 mb-0 py-10">
		<div class="container">
			<div
				class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8"
			>
				<div class="col-span-1">
					<h2
						class="text-3xl font-bold tracking-tight font-playfair-display italic"
					>
						<span class="text-white">Yolit's Bookish</span>
					</h2>
					<p class="text-white/80 text-sm mt-1 mb-0">
						Compulsive Reader, Book Blogger & Reviewer. Tu guía literaria
						bilingüe.
					</p>
					<!-- <div class="social-links">
						<a href="#" aria-label="Instagram"
							><i class="fab fa-instagram"></i
						></a>
						<a href="#" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
						<a href="#" aria-label="Goodreads"
							><i class="fab fa-goodreads"></i
						></a>
						<a href="#" aria-label="YouTube"><i class="fab fa-youtube"></i></a>
						<a href="#" aria-label="NetGalley"
							><i class="fas fa-book-open"></i
						></a>
					</div> -->
				</div>

				<div class="col-span-1">
					<h4 class="text-white text-lg font-bold mb-4">Secciones</h4>
					<ul class="list-none text-white/80 text-md font-nunito">
						<li class="hover:text-crimson-900 transition-all duration-300">
							<a href="#home">Inicio</a>
						</li>
						<li><a href="#reseñas">Reseñas</a></li>
						<li class="hover:text-crimson-900 transition-all duration-300">
							<a href="#blog">Blog</a>
						</li>
						<li class="hover:text-crimson-900 transition-all duration-300">
							<a href="#top10">Top 10 Tuesday</a>
						</li>
						<li class="hover:text-crimson-900 transition-all duration-300">
							<a href="#about">Sobre mí</a>
						</li>
					</ul>
				</div>

				<div class="col-span-1">
					<h4 class="text-white text-lg font-bold mb-4 font-oswald">
						Categorías
					</h4>
					<ul class="list-none text-white/80 text-sm font-nunito">
						<li class="hover:text-crimson-900 transition-all duration-300">
							<a href="#">Reseñas en Español</a>
						</li>
						<li class="hover:text-crimson-900 transition-all duration-300">
							<a href="#">Lecturas en Inglés</a>
						</li>
						<li class="hover:text-crimson-900 transition-all duration-300">
							<a href="#">ARC Reviews</a>
						</li>
						<li class="hover:text-crimson-900 transition-all duration-300">
							<a href="#">Monthly Wrap-Up</a>
						</li>
						<li class="hover:text-crimson-900 transition-all duration-300">
							<a href="#">WWW Wednesday</a>
						</li>
					</ul>
				</div>

				<!-- <div class="d-flex flex-col gap-2">
					<h4 class="text-white text-lg font-bold mb-4">Contacto</h4>
					<ul class="list-none text-white/80 text-md">
						<li>
							<a href="mailto:hola@yolitsbookish.com">hola@yolitsbookish.com</a>
						</li>
						<li><a href="#">Colaboraciones</a></li>
						<li><a href="#">Política de Privacidad</a></li>
					</ul>
				</div> -->
			</div>

			<div class="text-center text-white/80 mt-4 border-t border-white/10 pt-4">
				<p class="mb-0 text-white">
					&copy; {{ new Date().getFullYear() }} Yolit's Bookish. Todos los
					derechos reservados. | Diseñado con
					<i class="fas fa-heart" style="color: #e74c3c"></i> y muchas páginas
					leídas.
				</p>
			</div>
		</div>
	</footer>
</template>
